// Generated from the user's active Obsidian LaTeX Suite data.json.
export type LatexSuiteRule = {
  trigger: string;
  regex: boolean;
  flags: string;
  replacement: string | null;
  dynamic: "identityMatrix" | null;
  options: string;
  priority: number;
  description: string;
  sourceIndex: number;
};

export const LATEX_SUITE_RULES: LatexSuiteRule[] = [
  {
    "trigger": "([a-zA-Z])ddot",
    "regex": true,
    "flags": "",
    "replacement": "\\ddot{[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 1,
    "description": "",
    "sourceIndex": 62
  },
  {
    "trigger": "e\\xi sts",
    "regex": false,
    "flags": "",
    "replacement": "\\exists",
    "dynamic": null,
    "options": "mA",
    "priority": 1,
    "description": "",
    "sourceIndex": 128
  },
  {
    "trigger": "\\xii",
    "regex": false,
    "flags": "",
    "replacement": "x_{i}",
    "dynamic": null,
    "options": "mA",
    "priority": 1,
    "description": "",
    "sourceIndex": 85
  },
  {
    "trigger": "norm",
    "regex": false,
    "flags": "",
    "replacement": "\\lvert $0 \\rvert $1",
    "dynamic": null,
    "options": "mA",
    "priority": 1,
    "description": "",
    "sourceIndex": 200
  },
  {
    "trigger": "Norm",
    "regex": false,
    "flags": "",
    "replacement": "\\lVert $0 \\rVert $1",
    "dynamic": null,
    "options": "mA",
    "priority": 1,
    "description": "",
    "sourceIndex": 201
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx|leq|geq|neq|gg|ll|equiv|sim|propto|rightarrow|leftarrow|Rightarrow|Leftarrow|leftrightarrow|to|mapsto|cap|cup|in|sum|prod|exp|ln|log|det|dots|vdots|ddots|pm|mp|int|iint|iiint|oint)([A-Za-z])",
    "regex": true,
    "flags": "",
    "replacement": "\\[[0]] [[1]]",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 140
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx) tilde",
    "regex": true,
    "flags": "",
    "replacement": "\\tilde{\\[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 148
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx) hat",
    "regex": true,
    "flags": "",
    "replacement": "\\hat{\\[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 144
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx) dot",
    "regex": true,
    "flags": "",
    "replacement": "\\dot{\\[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 145
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx) bar",
    "regex": true,
    "flags": "",
    "replacement": "\\bar{\\[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 146
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx) vec",
    "regex": true,
    "flags": "",
    "replacement": "\\vec{\\[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 147
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx) und",
    "regex": true,
    "flags": "",
    "replacement": "\\underline{\\[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 149
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx) sr",
    "regex": true,
    "flags": "",
    "replacement": "\\[[0]]^{2}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 141
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx) cb",
    "regex": true,
    "flags": "",
    "replacement": "\\[[0]]^{3}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 142
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega|parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx) rd",
    "regex": true,
    "flags": "",
    "replacement": "\\[[0]]^{$0}$1",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 143
  },
  {
    "trigger": "([^\\\\])(parallel|perp|partial|nabla|hbar|ell|infty|oplus|ominus|otimes|oslash|square|star|dagger|vee|wedge|subseteq|subset|supseteq|supset|emptyset|exists|nexists|forall|implies|impliedby|iff|setminus|neg|lor|land|bigcup|bigcap|cdot|times|simeq|approx)",
    "regex": true,
    "flags": "",
    "replacement": "[[0]]\\[[1]]",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "Add backslash before symbols",
    "sourceIndex": 139
  },
  {
    "trigger": "([^\\\\])(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega)",
    "regex": true,
    "flags": "",
    "replacement": "[[0]]\\[[1]]",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "Add backslash before Greek letters",
    "sourceIndex": 138
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega),\\.",
    "regex": true,
    "flags": "",
    "replacement": "\\boldsymbol{\\[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 68
  },
  {
    "trigger": "\\\\(alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|vartheta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|omicron|pi|rho|varrho|sigma|Sigma|tau|upsilon|Upsilon|phi|varphi|Phi|chi|psi|omega|Omega)\\.,",
    "regex": true,
    "flags": "",
    "replacement": "\\boldsymbol{\\[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 69
  },
  {
    "trigger": "\\\\(arcsin|sin|arccos|cos|arctan|tan|csc|sec|cot)([A-Za-gi-z])",
    "regex": true,
    "flags": "",
    "replacement": "\\[[0]] [[1]]",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "Add space after trig funcs. Skips letter h to allow sinh, cosh, etc.",
    "sourceIndex": 162
  },
  {
    "trigger": "([^\\\\])(arcsin|sin|arccos|cos|arctan|tan|csc|sec|cot)",
    "regex": true,
    "flags": "",
    "replacement": "[[0]]\\[[1]]",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "Add backslash before trig funcs",
    "sourceIndex": 161
  },
  {
    "trigger": "\\\\(sinh|cosh|tanh|coth)([A-Za-z])",
    "regex": true,
    "flags": "",
    "replacement": "\\[[0]] [[1]]",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "Add space after hyperbolic trig funcs",
    "sourceIndex": 163
  },
  {
    "trigger": "\\\\mathbf{([A-Za-z])}(\\d)",
    "regex": true,
    "flags": "",
    "replacement": "\\mathbf{[[0]]}_{[[1]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 83
  },
  {
    "trigger": "pa([A-Za-z])([A-Za-z])",
    "regex": true,
    "flags": "",
    "replacement": "\\frac{ \\partial [[0]] }{ \\partial [[1]] } ",
    "dynamic": null,
    "options": "rm",
    "priority": 0,
    "description": "",
    "sourceIndex": 151
  },
  {
    "trigger": "\\\\hat{([A-Za-z])}(\\d)",
    "regex": true,
    "flags": "",
    "replacement": "\\hat{[[0]]}_{[[1]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 81
  },
  {
    "trigger": "\\\\vec{([A-Za-z])}(\\d)",
    "regex": true,
    "flags": "",
    "replacement": "\\vec{[[0]]}_{[[1]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 82
  },
  {
    "trigger": "([^\\\\])(exp|log|ln)",
    "regex": true,
    "flags": "",
    "replacement": "[[0]]\\[[1]]",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 51
  },
  {
    "trigger": "([A-Za-z])_(\\d\\d)",
    "regex": true,
    "flags": "",
    "replacement": "[[0]]_{[[1]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 80
  },
  {
    "trigger": "([a-zA-Z])tilde",
    "regex": true,
    "flags": "",
    "replacement": "\\tilde{[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 63
  },
  {
    "trigger": "([a-zA-Z])hat",
    "regex": true,
    "flags": "",
    "replacement": "\\hat{[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 59
  },
  {
    "trigger": "([a-zA-Z])bar",
    "regex": true,
    "flags": "",
    "replacement": "\\bar{[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 60
  },
  {
    "trigger": "([a-zA-Z])und",
    "regex": true,
    "flags": "",
    "replacement": "\\underline{[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 64
  },
  {
    "trigger": "([a-zA-Z])vec",
    "regex": true,
    "flags": "",
    "replacement": "\\vec{[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 65
  },
  {
    "trigger": "([a-zA-Z]),\\.",
    "regex": true,
    "flags": "",
    "replacement": "\\mathbf{[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 66
  },
  {
    "trigger": "([a-zA-Z])\\.,",
    "regex": true,
    "flags": "",
    "replacement": "\\mathbf{[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 67
  },
  {
    "trigger": "([^\\\\])(det)",
    "regex": true,
    "flags": "",
    "replacement": "[[0]]\\[[1]]",
    "dynamic": null,
    "options": "rmA",
    "priority": 0,
    "description": "",
    "sourceIndex": 57
  },
  {
    "trigger": "iden(\\d)",
    "regex": true,
    "flags": "",
    "replacement": null,
    "dynamic": "identityMatrix",
    "options": "mA",
    "priority": 0,
    "description": "N x N identity matrix",
    "sourceIndex": 217
  },
  {
    "trigger": "matrix",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{matrix}\n$0\n\\end{matrix}",
    "dynamic": null,
    "options": "MA",
    "priority": 0,
    "description": "",
    "sourceIndex": 189
  },
  {
    "trigger": "matrix",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{matrix}$0\\end{matrix}",
    "dynamic": null,
    "options": "nA",
    "priority": 0,
    "description": "",
    "sourceIndex": 195
  },
  {
    "trigger": "trace",
    "regex": false,
    "flags": "",
    "replacement": "\\mathrm{Tr}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 58
  },
  {
    "trigger": "tilde",
    "regex": false,
    "flags": "",
    "replacement": "\\tilde{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 75
  },
  {
    "trigger": "\\prod",
    "regex": false,
    "flags": "",
    "replacement": "\\prod_{${0:i}=${1:1}}^{${2:N}} $3",
    "dynamic": null,
    "options": "m",
    "priority": 0,
    "description": "",
    "sourceIndex": 95
  },
  {
    "trigger": "notin",
    "regex": false,
    "flags": "",
    "replacement": "\\not\\in",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 122
  },
  {
    "trigger": "iiint",
    "regex": false,
    "flags": "",
    "replacement": "\\iiint",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 158
  },
  {
    "trigger": "outer",
    "regex": false,
    "flags": "",
    "replacement": "\\ket{${0:\\psi}} \\bra{${0:\\psi}} $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 178
  },
  {
    "trigger": "cases",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{cases}\n$0\n\\end{cases}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 196
  },
  {
    "trigger": "align",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{align}\n$0\n\\end{align}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 197
  },
  {
    "trigger": "array",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{array}\n$0\n\\end{array}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 198
  },
  {
    "trigger": "floor",
    "regex": false,
    "flags": "",
    "replacement": "\\lfloor $0 \\rfloor $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 203
  },
  {
    "trigger": "conv",
    "regex": false,
    "flags": "",
    "replacement": "\\operatorname{conv}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 6
  },
  {
    "trigger": "span",
    "regex": false,
    "flags": "",
    "replacement": "\\operatorname{span}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 9
  },
  {
    "trigger": "text",
    "regex": false,
    "flags": "",
    "replacement": "\\text{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 39
  },
  {
    "trigger": "invs",
    "regex": false,
    "flags": "",
    "replacement": "^{-1}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 49
  },
  {
    "trigger": "conj",
    "regex": false,
    "flags": "",
    "replacement": "^{*}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 52
  },
  {
    "trigger": "ddot",
    "regex": false,
    "flags": "",
    "replacement": "\\ddot{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 73
  },
  {
    "trigger": "cdot",
    "regex": false,
    "flags": "",
    "replacement": "\\cdot",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 74
  },
  {
    "trigger": "prod",
    "regex": false,
    "flags": "",
    "replacement": "\\prod",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 93
  },
  {
    "trigger": "\\sum",
    "regex": false,
    "flags": "",
    "replacement": "\\sum_{${0:i}=${1:1}}^{${2:N}} $3",
    "dynamic": null,
    "options": "m",
    "priority": 0,
    "description": "",
    "sourceIndex": 94
  },
  {
    "trigger": "nabl",
    "regex": false,
    "flags": "",
    "replacement": "\\nabla",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 100
  },
  {
    "trigger": "para",
    "regex": false,
    "flags": "",
    "replacement": "\\parallel",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 104
  },
  {
    "trigger": "simm",
    "regex": false,
    "flags": "",
    "replacement": "\\sim",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 111
  },
  {
    "trigger": "sim=",
    "regex": false,
    "flags": "",
    "replacement": "\\simeq",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 112
  },
  {
    "trigger": "prop",
    "regex": false,
    "flags": "",
    "replacement": "\\propto",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 113
  },
  {
    "trigger": "sub=",
    "regex": false,
    "flags": "",
    "replacement": "\\subseteq",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 124
  },
  {
    "trigger": "sup=",
    "regex": false,
    "flags": "",
    "replacement": "\\supseteq",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 125
  },
  {
    "trigger": "eset",
    "regex": false,
    "flags": "",
    "replacement": "\\emptyset",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 126
  },
  {
    "trigger": "\\int",
    "regex": false,
    "flags": "",
    "replacement": "\\int $0 \\, d${1:x} $2",
    "dynamic": null,
    "options": "m",
    "priority": 0,
    "description": "",
    "sourceIndex": 154
  },
  {
    "trigger": "dint",
    "regex": false,
    "flags": "",
    "replacement": "\\int_{${0:0}}^{${1:1}} $2 \\, d${3:x} $4",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 155
  },
  {
    "trigger": "oint",
    "regex": false,
    "flags": "",
    "replacement": "\\oint",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 156
  },
  {
    "trigger": "iint",
    "regex": false,
    "flags": "",
    "replacement": "\\iint",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 157
  },
  {
    "trigger": "oinf",
    "regex": false,
    "flags": "",
    "replacement": "\\int_{0}^{\\infty} $0 \\, d${1:x} $2",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 159
  },
  {
    "trigger": "infi",
    "regex": false,
    "flags": "",
    "replacement": "\\int_{-\\infty}^{\\infty} $0 \\, d${1:x} $2",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 160
  },
  {
    "trigger": "msun",
    "regex": false,
    "flags": "",
    "replacement": "M_{\\odot}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 171
  },
  {
    "trigger": "pmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{pmatrix}\n$0\n\\end{pmatrix}",
    "dynamic": null,
    "options": "MA",
    "priority": 0,
    "description": "",
    "sourceIndex": 184
  },
  {
    "trigger": "bmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{bmatrix}\n$0\n\\end{bmatrix}",
    "dynamic": null,
    "options": "MA",
    "priority": 0,
    "description": "",
    "sourceIndex": 185
  },
  {
    "trigger": "Bmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{Bmatrix}\n$0\n\\end{Bmatrix}",
    "dynamic": null,
    "options": "MA",
    "priority": 0,
    "description": "",
    "sourceIndex": 186
  },
  {
    "trigger": "vmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{vmatrix}\n$0\n\\end{vmatrix}",
    "dynamic": null,
    "options": "MA",
    "priority": 0,
    "description": "",
    "sourceIndex": 187
  },
  {
    "trigger": "Vmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{Vmatrix}\n$0\n\\end{Vmatrix}",
    "dynamic": null,
    "options": "MA",
    "priority": 0,
    "description": "",
    "sourceIndex": 188
  },
  {
    "trigger": "pmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{pmatrix}$0\\end{pmatrix}",
    "dynamic": null,
    "options": "nA",
    "priority": 0,
    "description": "",
    "sourceIndex": 190
  },
  {
    "trigger": "bmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{bmatrix}$0\\end{bmatrix}",
    "dynamic": null,
    "options": "nA",
    "priority": 0,
    "description": "",
    "sourceIndex": 191
  },
  {
    "trigger": "Bmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{Bmatrix}$0\\end{Bmatrix}",
    "dynamic": null,
    "options": "nA",
    "priority": 0,
    "description": "",
    "sourceIndex": 192
  },
  {
    "trigger": "vmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{vmatrix}$0\\end{vmatrix}",
    "dynamic": null,
    "options": "nA",
    "priority": 0,
    "description": "",
    "sourceIndex": 193
  },
  {
    "trigger": "Vmat",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{Vmatrix}$0\\end{Vmatrix}",
    "dynamic": null,
    "options": "nA",
    "priority": 0,
    "description": "",
    "sourceIndex": 194
  },
  {
    "trigger": "ceil",
    "regex": false,
    "flags": "",
    "replacement": "\\lceil $0 \\rceil $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 202
  },
  {
    "trigger": "tayl",
    "regex": false,
    "flags": "",
    "replacement": "${0:f}(${1:x} + ${2:h}) = ${0:f}(${1:x}) + ${0:f}'(${1:x})${2:h} + ${0:f}''(${1:x}) \\frac{${2:h}^{2}}{2!} + \\dots$3",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "Taylor expansion",
    "sourceIndex": 216
  },
  {
    "trigger": "beg",
    "regex": false,
    "flags": "",
    "replacement": "\\begin{$0}\n$1\n\\end{$0}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 2
  },
  {
    "trigger": "vol",
    "regex": false,
    "flags": "",
    "replacement": "\\operatorname{vol}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 3
  },
  {
    "trigger": "sgn",
    "regex": false,
    "flags": "",
    "replacement": "\\operatorname{sgn}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 7
  },
  {
    "trigger": "sub",
    "regex": false,
    "flags": "",
    "replacement": "\\subset",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 11
  },
  {
    "trigger": "end",
    "regex": false,
    "flags": "",
    "replacement": "\\operatorname{End}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 14
  },
  {
    "trigger": "ome",
    "regex": false,
    "flags": "",
    "replacement": "\\omega",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 37
  },
  {
    "trigger": "Ome",
    "regex": false,
    "flags": "",
    "replacement": "\\Omega",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 38
  },
  {
    "trigger": "sts",
    "regex": false,
    "flags": "",
    "replacement": "_\\text{$0}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 45
  },
  {
    "trigger": "hat",
    "regex": false,
    "flags": "",
    "replacement": "\\hat{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 70
  },
  {
    "trigger": "bar",
    "regex": false,
    "flags": "",
    "replacement": "\\bar{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 71
  },
  {
    "trigger": "und",
    "regex": false,
    "flags": "",
    "replacement": "\\underline{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 76
  },
  {
    "trigger": "vec",
    "regex": false,
    "flags": "",
    "replacement": "\\vec{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 77
  },
  {
    "trigger": "vdo",
    "regex": false,
    "flags": "",
    "replacement": "\\vdots",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 78
  },
  {
    "trigger": "hom",
    "regex": false,
    "flags": "",
    "replacement": "\\hom",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 79
  },
  {
    "trigger": "xnn",
    "regex": false,
    "flags": "",
    "replacement": "x_{n}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 84
  },
  {
    "trigger": "xjj",
    "regex": false,
    "flags": "",
    "replacement": "x_{j}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 86
  },
  {
    "trigger": "xp1",
    "regex": false,
    "flags": "",
    "replacement": "x_{n+1}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 87
  },
  {
    "trigger": "ynn",
    "regex": false,
    "flags": "",
    "replacement": "y_{n}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 88
  },
  {
    "trigger": "yii",
    "regex": false,
    "flags": "",
    "replacement": "y_{i}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 89
  },
  {
    "trigger": "yjj",
    "regex": false,
    "flags": "",
    "replacement": "y_{j}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 90
  },
  {
    "trigger": "ooo",
    "regex": false,
    "flags": "",
    "replacement": "\\infty",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 91
  },
  {
    "trigger": "sum",
    "regex": false,
    "flags": "",
    "replacement": "\\sum",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 92
  },
  {
    "trigger": "lim",
    "regex": false,
    "flags": "",
    "replacement": "\\lim_{ ${0:n} \\to ${1:\\infty} } $2",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 96
  },
  {
    "trigger": "...",
    "regex": false,
    "flags": "",
    "replacement": "\\dots",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 99
  },
  {
    "trigger": "del",
    "regex": false,
    "flags": "",
    "replacement": "\\nabla",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 101
  },
  {
    "trigger": "===",
    "regex": false,
    "flags": "",
    "replacement": "\\equiv",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 105
  },
  {
    "trigger": "<->",
    "regex": false,
    "flags": "",
    "replacement": "\\leftrightarrow ",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 114
  },
  {
    "trigger": "and",
    "regex": false,
    "flags": "",
    "replacement": "\\cap",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 119
  },
  {
    "trigger": "orr",
    "regex": false,
    "flags": "",
    "replacement": "\\cup",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 120
  },
  {
    "trigger": "inn",
    "regex": false,
    "flags": "",
    "replacement": "\\in",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 121
  },
  {
    "trigger": "\\\\\\",
    "regex": false,
    "flags": "",
    "replacement": "\\setminus",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 123
  },
  {
    "trigger": "set",
    "regex": false,
    "flags": "",
    "replacement": "\\{ $0 \\}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 127
  },
  {
    "trigger": "par",
    "regex": false,
    "flags": "",
    "replacement": "\\frac{ \\partial ${0:y} }{ \\partial ${1:x} } $2",
    "dynamic": null,
    "options": "m",
    "priority": 0,
    "description": "",
    "sourceIndex": 150
  },
  {
    "trigger": "ddt",
    "regex": false,
    "flags": "",
    "replacement": "\\frac{d}{dt} ",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 152
  },
  {
    "trigger": "kbt",
    "regex": false,
    "flags": "",
    "replacement": "k_{B}T",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 170
  },
  {
    "trigger": "dag",
    "regex": false,
    "flags": "",
    "replacement": "^{\\dagger}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 172
  },
  {
    "trigger": "bra",
    "regex": false,
    "flags": "",
    "replacement": "\\bra{$0} $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 175
  },
  {
    "trigger": "ket",
    "regex": false,
    "flags": "",
    "replacement": "\\ket{$0} $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 176
  },
  {
    "trigger": "brk",
    "regex": false,
    "flags": "",
    "replacement": "\\braket{ $0 | $1 } $2",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 177
  },
  {
    "trigger": "cee",
    "regex": false,
    "flags": "",
    "replacement": "\\ce{ $0 }",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 180
  },
  {
    "trigger": "he4",
    "regex": false,
    "flags": "",
    "replacement": "{}^{4}_{2}He ",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 181
  },
  {
    "trigger": "he3",
    "regex": false,
    "flags": "",
    "replacement": "{}^{3}_{2}He ",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 182
  },
  {
    "trigger": "iso",
    "regex": false,
    "flags": "",
    "replacement": "{}^{${0:4}}_{${1:2}}${2:He}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 183
  },
  {
    "trigger": "avg",
    "regex": false,
    "flags": "",
    "replacement": "\\langle $0 \\rangle $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 199
  },
  {
    "trigger": "mod",
    "regex": false,
    "flags": "",
    "replacement": "\\bmod",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 204
  },
  {
    "trigger": "lr(",
    "regex": false,
    "flags": "",
    "replacement": "\\left( $0 \\right) $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 211
  },
  {
    "trigger": "lr{",
    "regex": false,
    "flags": "",
    "replacement": "\\left\\{ $0 \\right\\} $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 212
  },
  {
    "trigger": "lr[",
    "regex": false,
    "flags": "",
    "replacement": "\\left[ $0 \\right] $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 213
  },
  {
    "trigger": "lr|",
    "regex": false,
    "flags": "",
    "replacement": "\\left| $0 \\right| $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 214
  },
  {
    "trigger": "lra",
    "regex": false,
    "flags": "",
    "replacement": "\\left< $0 \\right> $1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 215
  },
  {
    "trigger": "mk",
    "regex": false,
    "flags": "",
    "replacement": "$$0$",
    "dynamic": null,
    "options": "tA",
    "priority": 0,
    "description": "",
    "sourceIndex": 0
  },
  {
    "trigger": "dm",
    "regex": false,
    "flags": "",
    "replacement": "$$\n$0\n$$",
    "dynamic": null,
    "options": "tAw",
    "priority": 0,
    "description": "",
    "sourceIndex": 1
  },
  {
    "trigger": "sr",
    "regex": false,
    "flags": "",
    "replacement": "\\blacksquare",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 4
  },
  {
    "trigger": "di",
    "regex": false,
    "flags": "",
    "replacement": "\\diamond",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 5
  },
  {
    "trigger": "ep",
    "regex": false,
    "flags": "",
    "replacement": "\\epsilon",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 8
  },
  {
    "trigger": "dg",
    "regex": false,
    "flags": "",
    "replacement": "\\operatorname{diag}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 10
  },
  {
    "trigger": "sm",
    "regex": false,
    "flags": "",
    "replacement": "setminus",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 12
  },
  {
    "trigger": "wd",
    "regex": false,
    "flags": "",
    "replacement": "\\wedge",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 13
  },
  {
    "trigger": "@a",
    "regex": false,
    "flags": "",
    "replacement": "\\alpha",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 15
  },
  {
    "trigger": "@b",
    "regex": false,
    "flags": "",
    "replacement": "\\beta",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 16
  },
  {
    "trigger": "@g",
    "regex": false,
    "flags": "",
    "replacement": "\\gamma",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 17
  },
  {
    "trigger": "@G",
    "regex": false,
    "flags": "",
    "replacement": "\\Gamma",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 18
  },
  {
    "trigger": "@d",
    "regex": false,
    "flags": "",
    "replacement": "\\delta",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 19
  },
  {
    "trigger": "@D",
    "regex": false,
    "flags": "",
    "replacement": "\\Delta",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 20
  },
  {
    "trigger": "@e",
    "regex": false,
    "flags": "",
    "replacement": "\\epsilon",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 21
  },
  {
    "trigger": ":e",
    "regex": false,
    "flags": "",
    "replacement": "\\varepsilon",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 22
  },
  {
    "trigger": "@z",
    "regex": false,
    "flags": "",
    "replacement": "\\zeta",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 23
  },
  {
    "trigger": "@t",
    "regex": false,
    "flags": "",
    "replacement": "\\theta",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 24
  },
  {
    "trigger": "@T",
    "regex": false,
    "flags": "",
    "replacement": "\\Theta",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 25
  },
  {
    "trigger": ":t",
    "regex": false,
    "flags": "",
    "replacement": "\\vartheta",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 26
  },
  {
    "trigger": "@i",
    "regex": false,
    "flags": "",
    "replacement": "\\iota",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 27
  },
  {
    "trigger": "@k",
    "regex": false,
    "flags": "",
    "replacement": "\\kappa",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 28
  },
  {
    "trigger": "@l",
    "regex": false,
    "flags": "",
    "replacement": "\\lambda",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 29
  },
  {
    "trigger": "@L",
    "regex": false,
    "flags": "",
    "replacement": "\\Lambda",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 30
  },
  {
    "trigger": "@s",
    "regex": false,
    "flags": "",
    "replacement": "\\sigma",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 31
  },
  {
    "trigger": "@S",
    "regex": false,
    "flags": "",
    "replacement": "\\Sigma",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 32
  },
  {
    "trigger": "@u",
    "regex": false,
    "flags": "",
    "replacement": "\\upsilon",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 33
  },
  {
    "trigger": "@U",
    "regex": false,
    "flags": "",
    "replacement": "\\Upsilon",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 34
  },
  {
    "trigger": "@o",
    "regex": false,
    "flags": "",
    "replacement": "\\omega",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 35
  },
  {
    "trigger": "@O",
    "regex": false,
    "flags": "",
    "replacement": "\\Omega",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 36
  },
  {
    "trigger": "sr",
    "regex": false,
    "flags": "",
    "replacement": "^{2}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 41
  },
  {
    "trigger": "cb",
    "regex": false,
    "flags": "",
    "replacement": "^{3}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 42
  },
  {
    "trigger": "rd",
    "regex": false,
    "flags": "",
    "replacement": "^{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 43
  },
  {
    "trigger": "sq",
    "regex": false,
    "flags": "",
    "replacement": "\\sqrt{ $0 }$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 46
  },
  {
    "trigger": "//",
    "regex": false,
    "flags": "",
    "replacement": "\\frac{$0}{$1}$2",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 47
  },
  {
    "trigger": "ee",
    "regex": false,
    "flags": "",
    "replacement": "e^{ $0 }$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 48
  },
  {
    "trigger": "Re",
    "regex": false,
    "flags": "",
    "replacement": "\\mathrm{Re}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 53
  },
  {
    "trigger": "Im",
    "regex": false,
    "flags": "",
    "replacement": "\\mathrm{Im}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 54
  },
  {
    "trigger": "bf",
    "regex": false,
    "flags": "",
    "replacement": "\\mathbf{$0}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 55
  },
  {
    "trigger": "rm",
    "regex": false,
    "flags": "",
    "replacement": "\\mathrm{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 56
  },
  {
    "trigger": "+-",
    "regex": false,
    "flags": "",
    "replacement": "\\pm",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 97
  },
  {
    "trigger": "-+",
    "regex": false,
    "flags": "",
    "replacement": "\\mp",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 98
  },
  {
    "trigger": "xx",
    "regex": false,
    "flags": "",
    "replacement": "\\times",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 102
  },
  {
    "trigger": "**",
    "regex": false,
    "flags": "",
    "replacement": "\\cdot",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 103
  },
  {
    "trigger": "!=",
    "regex": false,
    "flags": "",
    "replacement": "\\neq",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 106
  },
  {
    "trigger": ">=",
    "regex": false,
    "flags": "",
    "replacement": "\\geq",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 107
  },
  {
    "trigger": "<=",
    "regex": false,
    "flags": "",
    "replacement": "\\leq",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 108
  },
  {
    "trigger": ">>",
    "regex": false,
    "flags": "",
    "replacement": "\\gg",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 109
  },
  {
    "trigger": "<<",
    "regex": false,
    "flags": "",
    "replacement": "\\ll",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 110
  },
  {
    "trigger": "->",
    "regex": false,
    "flags": "",
    "replacement": "\\to",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 115
  },
  {
    "trigger": "!>",
    "regex": false,
    "flags": "",
    "replacement": "\\mapsto",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 116
  },
  {
    "trigger": "=>",
    "regex": false,
    "flags": "",
    "replacement": "\\implies",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 117
  },
  {
    "trigger": "=<",
    "regex": false,
    "flags": "",
    "replacement": "\\impliedby",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 118
  },
  {
    "trigger": "LL",
    "regex": false,
    "flags": "",
    "replacement": "\\mathcal{L}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 129
  },
  {
    "trigger": "HH",
    "regex": false,
    "flags": "",
    "replacement": "\\mathcal{H}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 130
  },
  {
    "trigger": "CC",
    "regex": false,
    "flags": "",
    "replacement": "\\mathbb{C}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 131
  },
  {
    "trigger": "RR",
    "regex": false,
    "flags": "",
    "replacement": "\\mathbb{R}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 132
  },
  {
    "trigger": "ZZ",
    "regex": false,
    "flags": "",
    "replacement": "\\mathbb{Z}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 133
  },
  {
    "trigger": "NN",
    "regex": false,
    "flags": "",
    "replacement": "\\mathbb{N}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 134
  },
  {
    "trigger": "QQ",
    "regex": false,
    "flags": "",
    "replacement": "\\mathbb{Q}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 135
  },
  {
    "trigger": "FF",
    "regex": false,
    "flags": "",
    "replacement": "\\mathbb{F}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 136
  },
  {
    "trigger": "AA",
    "regex": false,
    "flags": "",
    "replacement": "\\mathbb{A}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 137
  },
  {
    "trigger": "o+",
    "regex": false,
    "flags": "",
    "replacement": "\\oplus ",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 173
  },
  {
    "trigger": "ox",
    "regex": false,
    "flags": "",
    "replacement": "\\otimes ",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 174
  },
  {
    "trigger": "pu",
    "regex": false,
    "flags": "",
    "replacement": "\\pu{ $0 }",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 179
  },
  {
    "trigger": "\"",
    "regex": false,
    "flags": "",
    "replacement": "\\text{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 40
  },
  {
    "trigger": "_",
    "regex": false,
    "flags": "",
    "replacement": "_{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 44
  },
  {
    "trigger": "U",
    "regex": false,
    "flags": "",
    "replacement": "\\underbrace{ ${VISUAL} }_{ $0 }",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 164
  },
  {
    "trigger": "O",
    "regex": false,
    "flags": "",
    "replacement": "\\overbrace{ ${VISUAL} }^{ $0 }",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 165
  },
  {
    "trigger": "B",
    "regex": false,
    "flags": "",
    "replacement": "\\underset{ $0 }{ ${VISUAL} }",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 166
  },
  {
    "trigger": "C",
    "regex": false,
    "flags": "",
    "replacement": "\\cancel{ ${VISUAL} }",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 167
  },
  {
    "trigger": "K",
    "regex": false,
    "flags": "",
    "replacement": "\\cancelto{ $0 }{ ${VISUAL} }",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 168
  },
  {
    "trigger": "S",
    "regex": false,
    "flags": "",
    "replacement": "\\sqrt{ ${VISUAL} }",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 169
  },
  {
    "trigger": "(",
    "regex": false,
    "flags": "",
    "replacement": "(${VISUAL})",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 205
  },
  {
    "trigger": "[",
    "regex": false,
    "flags": "",
    "replacement": "[${VISUAL}]",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 206
  },
  {
    "trigger": "{",
    "regex": false,
    "flags": "",
    "replacement": "{${VISUAL}}",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 207
  },
  {
    "trigger": "(",
    "regex": false,
    "flags": "",
    "replacement": "($0)$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 208
  },
  {
    "trigger": "{",
    "regex": false,
    "flags": "",
    "replacement": "{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 209
  },
  {
    "trigger": "[",
    "regex": false,
    "flags": "",
    "replacement": "[$0]$1",
    "dynamic": null,
    "options": "mA",
    "priority": 0,
    "description": "",
    "sourceIndex": 210
  },
  {
    "trigger": "([A-Za-z])(\\d)",
    "regex": true,
    "flags": "",
    "replacement": "[[0]]_{[[1]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": -1,
    "description": "Auto letter subscript",
    "sourceIndex": 50
  },
  {
    "trigger": "([a-zA-Z])dot",
    "regex": true,
    "flags": "",
    "replacement": "\\dot{[[0]]}",
    "dynamic": null,
    "options": "rmA",
    "priority": -1,
    "description": "",
    "sourceIndex": 61
  },
  {
    "trigger": "([^\\\\])int",
    "regex": true,
    "flags": "",
    "replacement": "[[0]]\\int",
    "dynamic": null,
    "options": "mA",
    "priority": -1,
    "description": "",
    "sourceIndex": 153
  },
  {
    "trigger": "dot",
    "regex": false,
    "flags": "",
    "replacement": "\\dot{$0}$1",
    "dynamic": null,
    "options": "mA",
    "priority": -1,
    "description": "",
    "sourceIndex": 72
  }
];
export const LATEX_SUITE_SETTINGS = {
  "triggerKey": "Tab",
  "wordDelimiters": "., +-\\n\t:;!?\\/{}[]()=~$",
  "autofractionBreakingChars": "+-=\t",
  "matrixEnvironments": [
    "pmatrix",
    "cases",
    "align",
    "gather",
    "bmatrix",
    "Bmatrix",
    "vmatrix",
    "Vmatrix",
    "array",
    "matrix"
  ],
  "autoEnlargeTriggers": [
    "sum",
    "int",
    "frac",
    "prod",
    "bigcup",
    "bigcap"
  ]
} as const;

